local f = io.open('arrab.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 arrab.sh')
os.execute('killall -9 tg')
os.execute('rm -rf arrab.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('arrab.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 arrab.sh')
os.execute('screen ./arrab.sh')
